const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium,launchOptions}=require('./runtime.cjs');
const fixture=require('./fixture.cjs');
const root=path.resolve(__dirname,'../..'),baseline='released';
const baselineHtml=require('node:child_process').execFileSync('git',['show','d332145:FILIP-CRM.html'],{cwd:root,encoding:'utf8',maxBuffer:4*1024*1024});
(async()=>{
const browser=await chromium.launch(launchOptions);
const results=[];
async function session(dir){
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 const errors=[];context.on('page',p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource'))errors.push(m.text())});p.on('dialog',d=>d.type()==='confirm'?d.accept():d.dismiss());});
 await context.route('**/*',async route=>{
 const u=new URL(route.request().url());
 if(u.hostname==='crm.test'){if(dir===baseline&&u.pathname==='/FILIP-CRM.html')return route.fulfill({body:baselineHtml,contentType:'text/html'});const p=path.join(dir===baseline?root:dir,decodeURIComponent(u.pathname));if(fs.existsSync(p))return route.fulfill({body:fs.readFileSync(p),contentType:p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'text/html'});}
 if(u.hostname==='cdn.jsdelivr.net'){const file=u.pathname.includes('xlsx')?'xlsx.full.min.js':'chart.umd.min.js';return route.fulfill({body:fs.readFileSync(path.join(root,'assets/vendor',file)),contentType:'text/javascript'});}
 if(u.hostname==='127.0.0.1')return route.fulfill({status:503,body:'isolated'});
 return route.abort();
 });
 await context.addInitScript(data=>{if(location.hostname==='crm.test'&&!localStorage.getItem('filip_crm_main_v1'))localStorage.setItem('filip_crm_main_v1',JSON.stringify(data))},fixture);
 const page=await context.newPage();await page.goto('https://crm.test/FILIP-CRM.html');await page.waitForTimeout(1800);
 return{context,page,errors};
}
async function snapshot(page){return page.evaluate(()=>{
 renderAll();return{counts:{clients:state.clients.length,contracts:state.contracts.length,deals:state.deals.length,records:state.investmentRecords.length},deals:state.deals.map(d=>({id:d.id,bj:dealBJ(d),cash:dealCash(d),commission:dealActualCommission(d)})),classic:classicInvestmentItems().map(x=>({amount:x.amount,invested:investmentInvestedAmount(x),product:x.product})),fki:fkClientRows().map(x=>({aum:x.aum,invested:x.invested})),report:clientOverviewReportHtml(findClient(1),{summary:true,open:true,insurance:true,loans:true,investments:true,notice:true},'Test report')};})}
try{
 const old=await session(baseline),current=await session(root);
 const a=await snapshot(old.page),b=await snapshot(current.page);
 assert.deepEqual({...b,report:undefined},{...a,report:undefined});results.push('Portfolio, totals and commissions match released version');
 // Report rendering must retain the released client data while allowing corrected calculations and presentation.
 assert(b.report.includes('Testovací klient Alfa'));results.push('Client report retains released client data');
 console.log('baseline errors',old.errors);
 const {page,context,errors}=current;
 for(const view of await page.locator('.tab[data-view]').evaluateAll(xs=>xs.map(x=>x.dataset.view))){await page.locator(`.tab[data-view="${view}"]`).click();assert(await page.locator('#'+view).isVisible());}
 results.push('14 populated views');
 await page.evaluate(()=>{showView('clients');selectClient(1);clientSection='overview';renderClientDetail()});
 const aum=await page.evaluate(()=>{const pension=clientPensionSummary(1).total,total=clientInvestmentSummary(1).total+pension,text=byId('clientDetail').innerText;return{pension,total,hasLabel:text.includes('AUM klienta celkem'),hasTotal:text.includes(money(total))}});
 assert.equal(aum.pension,1500);assert(aum.hasLabel);assert(aum.hasTotal);results.push('Client AUM includes pensions separately');
 const clientContact=await page.evaluate(()=>{const c=findClient(1);c.address='Testovací 1, Praha';renderClientDetail();return{age:clientAgeFromBirthId(c.birthId),ageText:byId('clientDetail').querySelector('.client-age')?.textContent||'',phoneCopies:byId('clientDetail').querySelectorAll('.contact-grid .contact-value').length,phoneCall:byId('clientDetail').querySelector('a[href^="tel:"]')?.textContent,emailCopy:[...byId('clientDetail').querySelectorAll('.contact-actions .copy-btn')].some(x=>x.textContent==='Kopírovat'),addressMap:byId('clientDetail').querySelector('.contact-actions a[href^="https://maps.google.com/"]')?.textContent}});
 assert(clientContact.age!==null);assert(clientContact.ageText.includes(String(clientContact.age)));assert.equal(clientContact.phoneCopies,3);assert.equal(clientContact.phoneCall,'Volat');assert(clientContact.emailCopy);assert.equal(clientContact.addressMap,'Mapa');results.push('Client age and contact copy actions');
 const referralLinks=await page.evaluate(()=>{const source=findClient(1),target=findClient(2);target.leadType='tipar';target.leadSource=clientName(source);target.leadDate='2026-03-01';state.referrals.push({id:51,from:clientName(source),to:'Nováková Eva',topic:'Doporučení na investice',date:'2026-04-02'});selectedClientId=1;clientSection='overview';renderClientDetail();const overview=byId('clientDetail').innerText;const chip=[...byId('clientDetail').querySelectorAll('.chips button')].find(x=>x.textContent.includes('Natipoval'));chip.click();const recommendations=byId('clientDetail').innerText;clientSection='overview';renderClientDetail();const openTarget=[...byId('clientDetail').querySelectorAll('.referral-overview button')].find(x=>x.textContent==='Otevřít klienta');openTarget.click();return{overview,recommendations,targetOverview:byId('clientDetail').innerText,selected:selectedClientId,tipCount:clientTiparLeads(source),recommendationCount:clientGivenRecommendations(source)}});
 assert(referralLinks.overview.includes('Testovací klient Beta'));assert(referralLinks.overview.includes('Nováková Eva'));assert(referralLinks.recommendations.includes('Koho klient doporučil nebo natipoval'));assert(referralLinks.recommendations.includes('Testovací klient Beta'));assert(referralLinks.targetOverview.includes('Klienta přivedl typař'));assert(referralLinks.targetOverview.includes('Testovací klient Alfa'));assert.equal(referralLinks.selected,2);assert.equal(referralLinks.tipCount,1);assert.equal(referralLinks.recommendationCount,1);results.push('Client card lists and opens named tips and recommendations');
 const productLinks=await page.evaluate(()=>{showView('clients');selectClient(1);clientSection='portfolio';renderClientDetail();byId('clientDetail').querySelector('[data-portfolio-area="fki"] button').click();const fki={visible:byId('fki').classList.contains('active'),selected:selectedFkClientId,detail:byId('fkDetail').innerText,hidden:byId('fki').querySelector('.investment-shell').classList.contains('clients-hidden'),button:byId('fkClientListToggle').textContent};toggleInvestmentClientList('fki');fki.revealed=!byId('fki').querySelector('.investment-shell').classList.contains('clients-hidden');showView('clients');clientSection='portfolio';renderClientDetail();byId('clientDetail').querySelector('[data-portfolio-area="investice"] button').click();return{fki,investment:{visible:byId('investments').classList.contains('active'),selected:selectedInvestmentClientId,detail:byId('investmentDetail').innerText,hidden:byId('investments').querySelector('.investment-shell').classList.contains('clients-hidden'),button:byId('investmentClientListToggle').textContent}}});
 assert(productLinks.fki.visible);assert.equal(productLinks.fki.selected,1);assert(productLinks.fki.detail.includes('Testovací klient Alfa'));assert(productLinks.fki.hidden);assert.equal(productLinks.fki.button,'Zobrazit klienty');assert(productLinks.fki.revealed);assert(productLinks.investment.visible);assert.equal(productLinks.investment.selected,1);assert(productLinks.investment.detail.includes('Testovací klient Alfa'));assert(productLinks.investment.hidden);assert.equal(productLinks.investment.button,'Zobrazit klienty');results.push('Client product links retain the selected client and hide other clients');
 const taxTests=await page.evaluate(()=>{const classicKey=investmentFundKey(classicInvestmentItems().find(x=>String(x.clientId||x.client?.id)==='1'));const fkiRow=fkClientRows().find(r=>String(r.client?.id)==='1');const fkiItem=fkiRow.items[0];state.fundValues[classicKey]={...(state.fundValues[classicKey]||{}),area:'investice',taxMonths:36};state.fundValues[fkiItem.key]={...(state.fundValues[fkiItem.key]||{}),area:'fki',taxMonths:36};showView('investments');selectInvestmentClient(1);const investmentText=byId('investmentDetail').innerText;showView('fki');selectFkClient(1);const fkiText=byId('fkDetail').innerText;const items=clientOutput_xClientInvestments(findClient(1));const classic=items.find(x=>x.area==='Investice');const reportFund=clientOutput_xFundDetail(classic,0,false);return{leap:liquidity_liquidityInfo('investice',classicKey,classic.isin,'2024-02-29').taxReady,regular:liquidity_liquidityInfo('investice',classicKey,classic.isin,'2026-01-10').taxReady,unknown:liquidity_investmentTaxStart({sourceType:'snapshot',date:'2026-09-01',snapshot:{date:'2026-09-01'}}),investmentText,fkiText,reportFund}});
 assert.equal(taxTests.leap,'2027-02-28');assert.equal(taxTests.regular,'2029-01-10');assert.equal(taxTests.unknown,'');assert(taxTests.investmentText.includes('10. 1. 2029'));assert(taxTests.fkiText.includes('10. 2. 2029'));assert(taxTests.reportFund.includes('10. 1. 2029'));assert(!taxTests.reportFund.includes('<small>Časový test</small><b>k '));results.push('36-month tax test uses purchase date in client cards and report');
 const forecastBase=await page.evaluate(()=>{const managedBefore=clientInvestmentSummary(1).total,reportBefore=reportInvestmentItems().reduce((s,x)=>s+(+x.amount||0),0);selectedClientId=1;openExternalInvestmentModal(1);setVal('externalProduct','Externí portfolio');setVal('externalCompany','Jiný správce');setVal('externalCurrent','500000');setVal('externalInvested','450000');setVal('externalMonthly','2000');setVal('externalRate','4');setVal('externalAsset','Smíšené');saveExternalInvestment();openInvestmentScenarioModal(1,'Investice');return{managedBefore,managedAfter:clientInvestmentSummary(1).total,reportBefore,reportAfter:reportInvestmentItems().reduce((s,x)=>s+(+x.amount||0),0)}});await page.waitForTimeout(100);
 const forecastSetup={...forecastBase,...await page.evaluate(()=>{setVal('scenarioForecastName','Test klientských variant');setVal('scenarioYears','10');setVal('scenarioSaveMode','forecast');investmentScenario.rows=[{key:'Investice|test-classic',area:'Investice',company:'Test invest',product:'Test nový nákup',amount:100000,monthly:1500,rate:6,minRate:4,maxRate:8,funding:'new'},{key:'FKI|test-fki',area:'FKI',company:'Test FKI',product:'Test nový nákup FKI',amount:300000,monthly:0,rate:8,minRate:6,maxRate:10,funding:'new'}];const positions=scenario_currentPositions(),external=positions.find(x=>x.sourceType==='external'),managed=positions.find(x=>x.sourceType==='managed'),targets=scenario_catalog().slice(0,2);investmentScenario.rows.push({...targets[0],amount:60000,monthly:0,funding:'reinvest',salePositionId:external.positionId,newTaxTest:true,source:'Nový nákup z odprodeje Externí portfolio'},{...targets[1],amount:40000,monthly:0,funding:'reinvest',salePositionId:external.positionId,newTaxTest:true,source:'Nový nákup z odprodeje Externí portfolio'});investmentScenario.dispositions={[managed.positionId]:{action:'transfer',amount:50000,targetKey:targets[0].key}};scenario_reconcileReinvestments();renderInvestmentScenario();scenario_syncActiveVariant();const first=investmentScenario.variants[0];first.name='Alternativa A';const pA=scenario_projection({years:10,rows:first.rows,dispositions:first.dispositions,externalRows:investmentScenario.externalRows});scenario_addVariant();scenario_renameVariant('Alternativa B');scenario_syncActiveVariant();const oldAlert=window.alert;window.alert=()=>{};scenario_addVariant();window.alert=oldAlert;const p=scenario_projection();return{external:p.externalAum,current:p.current,improvement:p.improvement,start:p.totalSeries[0],today:p.yearRows[0].total,weighted:p.weighted,plannedExisting:p.plannedExistingCapital,plannedNew:p.plannedNewCapital,variantA:{sold:pA.soldTotal,transfer:pA.transferTotal,newMoney:pA.newMoney,reinvested:pA.reinvestedTotal,start:pA.startingValue},variantCount:investmentScenario.variants.length,chartLabels:investmentScenarioChartInstance.data.datasets.map(x=>x.label),panel:byId('scenarioAdvancedControls').textContent,minRateField:!!byId('scenarioMinRate'),rangeBlock:!!byId('scenarioRangeBlock'),positionPlan:byId('scenarioCurrentPortfolio').textContent,opps:state.opportunities.length,deals:state.deals.length}})};
 assert.equal(forecastSetup.managedAfter,forecastSetup.managedBefore);assert.equal(forecastSetup.reportAfter,forecastSetup.reportBefore);assert.equal(forecastSetup.external,500000);assert(forecastSetup.current>forecastSetup.managedBefore);assert.equal(forecastSetup.start,forecastSetup.current+400000);assert.equal(forecastSetup.today,forecastSetup.start);assert(forecastSetup.weighted>0&&forecastSetup.weighted<20);assert(forecastSetup.plannedExisting>0);assert(forecastSetup.plannedNew>0);assert.equal(forecastSetup.variantCount,2);assert.equal(forecastSetup.variantA.sold,100000);assert.equal(forecastSetup.variantA.transfer,50000);assert.equal(forecastSetup.variantA.newMoney,500000);assert.equal(forecastSetup.variantA.reinvested,100000);assert.equal(forecastSetup.variantA.start,forecastSetup.current-100000+500000);assert.deepEqual(forecastSetup.chartLabels,['Očekávaný vývoj']);assert(forecastSetup.panel.includes('Průměrné očekávané zhodnocení'));assert(forecastSetup.panel.includes('nový časový test'));assert(forecastSetup.positionPlan.includes('rozděleno do nových nákupů'));assert(!forecastSetup.panel.includes('Optimisticky'));assert.equal(forecastSetup.minRateField,false);assert.equal(forecastSetup.rangeBlock,false);assert(forecastSetup.improvement>0);await page.screenshot({path:'/private/tmp/crm-investment-forecast.png',fullPage:true});
 const forecastSaved=await page.evaluate(before=>{saveInvestmentScenario();const saved=state.investmentForecasts.at(-1);return{saved,opps:state.opportunities.length,deals:state.deals.length,activity:state.activities.find(x=>x.type==='Investiční prognóza'&&x.clientId===1),panel:byId('clientDetail').innerText}},forecastSetup);
 assert(forecastSaved.saved);assert.equal(forecastSaved.saved.variants.length,2);assert.equal(forecastSaved.opps,forecastSetup.opps);assert.equal(forecastSaved.deals,forecastSetup.deals);assert(forecastSaved.activity);assert(forecastSaved.panel.includes('Test klientských variant'));results.push('External assets stay outside AUM and saved variants create no business');
 const forecastDownload=page.waitForEvent('download');await page.evaluate(id=>downloadSavedInvestmentForecast(id),forecastSaved.saved.id);const forecastFile=await forecastDownload;const forecastHtml=fs.readFileSync(await forecastFile.path(),'utf8');assert(forecastHtml.includes('Aktuální portfolio'));assert(forecastHtml.includes('Fondy'));assert(forecastHtml.includes('Segmenty'));assert(forecastHtml.includes('Likvidita'));assert(forecastHtml.includes('Alternativa A'));assert(forecastHtml.includes('Alternativa B'));assert(forecastHtml.includes('novými časovými testy'));const forecastPage=await context.newPage();await forecastPage.setViewportSize({width:850,height:1180});await forecastPage.setContent(forecastHtml);await forecastPage.screenshot({path:'/private/tmp/crm-investment-variants-report.png',fullPage:true});const forecastPdf=await forecastPage.pdf({path:'/private/tmp/crm-investment-variants-report.pdf',format:'A4',printBackground:true});assert(forecastPdf.length>10000);assert.equal(forecastPdf.subarray(0,4).toString(),'%PDF');await forecastPage.close();results.push('Saved investment variants download as compact portrait one-page comparison');
 await page.evaluate(id=>openSavedInvestmentForecast(id),forecastSaved.saved.id);await page.waitForTimeout(100);const reopenedForecast=await page.evaluate(()=>({open:byId('investmentScenarioModal').classList.contains('show'),name:val('scenarioForecastName'),external:(investmentScenario.externalRows||[]).length,proposal:(investmentScenario.rows||[]).length,variants:(investmentScenario.variants||[]).length,dispositions:Object.keys(investmentScenario.dispositions||{}).length}));assert(reopenedForecast.open);assert.equal(reopenedForecast.name,'Test klientských variant');assert.equal(reopenedForecast.external,1,'saved external rows');assert.equal(reopenedForecast.proposal,4,'saved proposal rows');assert.equal(reopenedForecast.variants,2,'saved variants');assert(reopenedForecast.dispositions>=2,'saved sale and transfer');await page.evaluate(()=>closeModal('investmentScenarioModal'));results.push('Saved investment variants reopen for further client work');
 const familyCheck=await page.evaluate(()=>{selectedClientId=1;openFamilyLink(1);setVal('familyPerson','2');setVal('familyType','child');byId('familyManaged').checked=true;saveFamilyLink();const forward=findClient(1).familyLinks[0],reverse=findClient(2).familyLinks[0];openFamilyLink(1);setVal('familyName','Test dítě rodiny');saveFamilyLink();const created=state.clients.find(c=>c.name==='Test dítě rodiny');const restored=normalizeState(JSON.parse(JSON.stringify(state)));return {forward,reverse,created:!!created,preserved:restored.clients.find(c=>c.id===1).familyLinks.length};});
 assert.equal(familyCheck.forward.type,'child');assert.equal(familyCheck.reverse.type,'parent');assert(familyCheck.forward.managedByParent);assert(familyCheck.created);assert.equal(familyCheck.preserved,2);results.push('Family links are reciprocal, support new clients and survive backup normalization');
 const payoutCheck=await page.evaluate(()=>{const d=state.deals[0];d.owner='Test tipař';d.ownerType='tipar';d.ownerPaid=false;openOwnerLedger('Test tipař');const before=byId('ownerLedgerModal').innerText;setVal('ownerDate'+d.id,'2026-09-20');setVal('ownerNote'+d.id,'Ověřeno v bankovním výpisu');recordOwnerPayment(d.id,true);const result={before,paid:d.ownerPaid,date:d.ownerPaidDate,history:d.ownerPaymentHistory.length,after:byId('ownerLedgerModal').innerText};closeModal('ownerLedgerModal');return result;});assert(payoutCheck.before.includes('Bez záznamu výplaty'));assert(payoutCheck.paid);assert.equal(payoutCheck.date,'2026-09-20');assert.equal(payoutCheck.history,1);assert(payoutCheck.after.includes('Vyplaceno'));results.push('Referrer payment ledger records date and audit history');
 await page.setViewportSize({width:1920,height:1080});assert(await page.locator('.app').evaluate(el=>el.getBoundingClientRect().width>1850));await page.screenshot({path:'/private/tmp/crm-family-wide.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
 const campaign=await page.evaluate(()=>{showView('campaigns');setVal('campaignSenderEmail','advisor@example.test');setVal('campaignName','Test investiční kampaně');setVal('campaignSubject','Test investiční novinky');setVal('campaignBody','Dobrý den, toto je testovací zpráva.');setVal('campaignSegment','investice');renderCampaignRecipients(true);const candidates=campaignRecipientRows.map(x=>x.client.id);window.__campaignMailto='';campaignLaunchMailto=url=>window.__campaignMailto=url;confirmCampaignEmail();const saved=state.campaigns.at(-1);return{candidates,saved,activity:state.activities.find(x=>x.campaignId===saved?.id),mailto:window.__campaignMailto,history:byId('campaignHistory').innerText}});
 assert.deepEqual(campaign.candidates,[1]);assert.deepEqual(campaign.saved.recipientIds,[1]);assert.equal(campaign.activity.type,'Smart emailing');assert(campaign.mailto.startsWith('mailto:advisor%40example.test?'));assert(campaign.mailto.includes('bcc=alfa%40example.test'));assert(campaign.history.includes('Test investiční kampaně'));results.push('Campaign selection, BCC handoff and client history');
 await page.screenshot({path:'/private/tmp/crm-unified-campaigns.png',fullPage:true});
 for(const expr of ["selectClient(1)","selectInvestmentClient(1)","selectFkClient(1)","selectPensionClient(1)","openClientModal(1)","openContractModal(1,10)","openDealModal(1,20)","openOpportunityModal(1,30)","openActivityModal(1,40)","openInvestmentFundModal()","openFkFundModal()","openInvestmentScenarioModal(1,'FKI')"]){await page.evaluate(expr);await page.evaluate(()=>document.querySelectorAll('.modal.show').forEach(x=>x.classList.remove('show')))}
 results.push('Client, investment, pension and editing dialogs');
 // Exercise real downloads; generated reports must be usable as independent files.
 for(const [name,action] of [['client',"openClientReportModal(1);downloadClientReport()"],['fki',"downloadFkClientReport(1)"],['scenario',"openInvestmentScenarioModal(1,'FKI');investmentScenario.rows=[{key:'test-fki',area:'FKI',company:'Test FKI',product:'Test FKI fond',isin:'TEST00000002',amount:50000,rate:7,minRate:4,maxRate:9}];downloadInvestmentScenario()"]]){
  const pending=page.waitForEvent('download');await page.evaluate(action);const download=await pending;assert(download.suggestedFilename().endsWith('.html'));
  const report=fs.readFileSync(await download.path(),'utf8');assert(report.includes('Testovací klient Alfa'));assert(!report.includes('NaN'));assert(!report.includes('undefined'));
  if(name==='scenario'){assert(report.includes('Skladba nového nákupu'));assert(report.includes('Model vývoje portfolia'));assert(report.includes('Navržené fondy'));assert(report.includes('Test FKI fond'));}
  const reportPage=await context.newPage();await reportPage.setContent(report);await reportPage.waitForTimeout(150);assert((await reportPage.locator('body').innerText()).length>100);if(name==='scenario')await reportPage.screenshot({path:'/private/tmp/crm-investment-purchase-report.png',fullPage:true});const pdf=await reportPage.pdf({format:'A4',printBackground:true});assert(pdf.length>10000);await reportPage.close();
  results.push(name+' HTML download opens independently');
 }
 await page.evaluate(()=>{document.querySelectorAll('.modal.show').forEach(x=>x.classList.remove('show'));showView('referrers');setVal('quickCallDate','2026-09-16');setVal('quickCallOutcome','realized');setVal('quickCallNext','Schůzka');setVal('quickCallNextDate','2026-09-23');saveQuickAnalysis('call')});
 const dates=await page.evaluate(()=>state.analysisEntries.slice(-2).map(x=>x.date));assert.deepEqual(dates,['2026-09-16','2026-09-23']);results.push('Call and follow-up use separate dates');

 // Create and edit a client through the production form handlers.
 const newId=await page.evaluate(()=>{openClientModal();setVal('cName','Test nový klient');setVal('cEmail','new@example.test');saveClient();return state.clients.find(c=>c.name==='Test nový klient').id});
 assert(newId);await page.evaluate(id=>{openClientModal(id);setVal('cPhone','123456789');saveClient()},newId);
 assert.equal(await page.evaluate(id=>findClient(id).phone,newId),'123456789');results.push('Client creation and edit persist');
 const proposal=await page.evaluate(()=>{openInvestmentScenarioModal(1,'FKI');investmentScenario.rows=[{key:'test-fki',area:'FKI',company:'Test FKI',product:'Test návrh FKI',isin:'TEST00000003',amount:75000,rate:6}];setVal('scenarioSaveMode','proposal');const before=state.deals.length;saveInvestmentScenario();return {dealDelta:state.deals.length-before,found:state.opportunities.some(o=>o.product==='Test návrh FKI')}});
 assert.equal(proposal.dealDelta,0);assert(proposal.found);results.push('Investment proposal stays out of completed trades');
 const signed=await page.evaluate(()=>{openInvestmentScenarioModal(2,'FKI');investmentScenario.rows=[{key:'test-fki',area:'FKI',company:'Test FKI',product:'Test sjednané FKI',isin:'TEST00000004',amount:80000,rate:6}];setVal('scenarioSaveMode','signed');setVal('scenarioSignedDate','2026-09-16');const before=state.deals.length;saveInvestmentScenario();return {dealDelta:state.deals.length-before,records:investmentRecordsForClient(2).length}});
 assert.equal(signed.dealDelta,1);assert(signed.records>0);results.push('Signed FKI creates trade and linked holding');
 const restore=await page.evaluate(()=>{const saved=JSON.parse(JSON.stringify(state));const expected=state.clients.length;state.clients.push({id:999,name:'Temporary test'});restoreIncomingStateFromGoogle(saved,'qa');return state.clients.length===expected});assert(restore);results.push('Backup restore preserves complete state schema');
 const queue=await page.evaluate(async()=>{
  clearTimeout(diskSaveTimer);diskLoadDone=true;diskSaveInFlight=false;diskSavePending=false;
  const originalFetch=window.fetch;let respond;const bodies=[];
  window.fetch=async(url,opts)=>{bodies.push(JSON.parse(opts.body).state);return new Promise(resolve=>respond=()=>resolve({ok:true,json:async()=>({ok:true,state:bodies[bodies.length-1],counts:{}})}))};
  const request=saveStateToDisk('test');state.clients[0].note='new edit during slow save';await saveStateToDisk('second edit');respond();await request;
  const retained=state.clients[0].note==='new edit during slow save';
  clearTimeout(diskSaveTimer);const follow=saveStateToDisk('follow-up');respond();await follow;window.fetch=originalFetch;diskLoadDone=false;
  return {retained,latest:bodies[1].clients[0].note};
 });assert(queue.retained);assert.equal(queue.latest,'new edit during slow save');results.push('Slow disk response cannot overwrite newer edits');
 await page.evaluate(()=>{showView('dashboard');const a=state.activities.find(x=>x.id===40);a.completed=false;a.date=today();renderDashboard()});
 await page.locator('[data-dash-action="done"][data-id="40"]').click();assert.equal(await page.evaluate(()=>state.activities.find(x=>x.id===40).outcome),'realized');results.push('Dashboard uses the shared activity completion action');
 await page.evaluate(()=>{showView('fki');selectFkClient(1)});await page.screenshot({path:'/private/tmp/crm-unified-fki.png',fullPage:true});
 await page.setViewportSize({width:834,height:1112});await page.screenshot({path:'/private/tmp/crm-unified-ipad.png',fullPage:true});results.push('iPad viewport rendered');
 console.log('current errors',errors);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:results},null,2));
 fs.writeFileSync('/private/tmp/crm-regression-results.json',JSON.stringify({passed:results},null,2));
 await old.context.close();await context.close();
}finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
